### ISSUE TITLE
Verify data of dataframe against manifest

### ISSUE THREAD

**Issue by NielsRogge** [ml6team/fondant#141]
As pointed out in https://github.com/ml6team/fondant/pull/104#discussion_r1195189732, currently the `evolve` method just updates the manifest without checking whether the corresponding output dataframe of a component actually contains the appropriate data, columns and types.

We need to check this.

**Comment by RobbeSneyders** [comment]
Adding some additional information:

The following checks are currently happening:
- In the `PandasTransformComponent`, the returned dataframe is validated against the `produces` section of the component spec by leveraging the `meta` keyword on the `map_partitions` method. https://github.com/ml6team/fondant/blob/4e9923ced12e3eed90e5f45738f05fec2412eb18/fondant/component.py#L304-L316
This check is correct since it validates the returned data against the `produces` section, but I'm not sure if / in which detail it validates data types.

- The `DaskDataWriter` validates the written data against the `produces` section of the component spec by extracting data from the 
https://github.com/ml6team/fondant/blob/4e9923ced12e3eed90e5f45738f05fec2412eb18/fondant/data_io.py#L103-L108
https://github.com/ml6team/fondant/blob/4e9923ced12e3eed90e5f45738f05fec2412eb18/fondant/data_io.py#L121-L139
This check is not ideal since it validates the written data against the `produces` section. Instead, we should
  - Check the data returned by the user against the `produces` section of the component spec
  - Check the written data against the output manifest, since this might contain additional data (see #244)
 
  It also doesn't validate data types, which we should do at least when writing the data.
