### ISSUE TITLE
Use the Dask.distributed.LocalCluster

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#395]
The clusters provided by `dask.distributed` are more performant and offer more control than the schedulers used by vanilla `dask`. It also looks like it is the main focus of current and future development in `dask`.

We should investigate if we can use the `LocalCluster` from `dask.distributed`, which still runs on a single machine, but provides a lot of benefits.

**Comment by mrchtr** [comment]
I have taken a look at how we could implement this. I think the right place to incorporate this usage would be in the `Executor`.

I would add the `client` to the class attributes of the `Executor`. This would give us the possibility to configure the client based on initialization arguments, which can be defined in the spec file later on.

Technically, it is possible to have several clients in one Python session, but only one client can be active at a time. To prevent the overwriting of these settings, I would propose modifying the `DaskDataLoader`. I would suggest assigning the client to the dataset so that, for every computation, the defined client of the executor will be used.
Assignment of a client can be done be calling: `dataframe = dataframe.persist(client=client)`


Below, you can find pseudocode illustrating how I see the changes.

```python
from distributed import Client
import dask.dataframe as dd
from dask.distributed import LocalCluster, performance_report

dummy_dataframe = dd.from_dict({"id": [0, 1, 2, 3], "url": ["a", "b", "c", "d"]}, npartitions=2)

class DaskDataLoader():
    def load_dataframe(self, client=None):
        # fondant code
        # ...
        dataframe = dummy_dataframe

        if client:
            return dataframe.persist(client=client)

class Executer():
    def __init__(self):
        # Set arguments for localcluster, provide definition in component spec?
        worker_kwargs = {
            "n_workers": 1,
            "memory_limit": 2e9,
            "threads_per_worker": 1
        }

        self.client = Client(LocalCluster(**worker_kwargs))

    def _execute_component(self):
        data_loader = DummyDaskDataLoader(
           # manifest=manifest,
           # component_spec=self.spec,
           # input_partition_rows=self.input_partition_rows,
        )

        dataframe = data_loader.load_dataframe(self.client)

        # ...

        return dataframe

if __name__ == '__main__':
    executer = DummyExecuter()
    dataframe = executer._execute_component()
    dataframe = dummy_dataframe
    dataframe["column"] = "hello world"
    
    # If we want to store the dashboard as static html we need to use the context manager wrapping around the final execution
    with performance_report(filename="export.html"):
        dataframe.compute()
```

Since the executor is used for the execution of every component, we will ensure that the client is used properly. Additionally, we could expose port `8787` of the local runner to access the dashboard UI. To enable static HTML export, we need to wrap the execution in a context manager using the performance_report method. This should be handled in #331

**Comment by PhilippeMoussalli** [comment]
Thanks @mrchtr! 

I think overall the approach looks good. I think that the client should be initialized at the `executor` level since that's the starting point of the execution and then it will be passed on to `data_io` where it will be used. 

However, I don't think we should call `dataframe.compute()` since this persists all the data in memory and could lead to OOM issues. We should probably pass all the write tasks that we create to the client at the end to compute. 

right now we have 
```python 
  with ProgressBar():
      logging.info("Writing data...")
      dd.compute(*write_tasks)
```

and we should move to something like this: 

```python 

with ProgressBar():
    logging.info("Writing data...")
    client.compute(*write_tasks)
```
where the write task is just a delayed computation that sinks directly to disk (thus avoiding OOM issues)

```python
write_task_1 = subset_1.to_parquet('/tmp/some.parquet', compute=False)
```

Taken from [here](https://docs.dask.org/en/latest/futures.html#:~:text=client.compute(ddf.to_parquet(%27/tmp/some.parquet%27%2C%20compute%3DFalse))).

Other remarks: 

1) We probably don't want to fix the client for all the components and provide a way to interactively select one with appropriate kwargs (e.g. some components might run on a `DistributedCluster `while others might just use a `LocalCluster`). We would need to provide a way to dynamically set this up before we run the component. Perhaps at the componentOp level along with the relevent kwargs 

```python
component_op = ComponentOp(
  component_dir="components/generic_component",
  cluster_type="local",
  worker_kwargs={...}
)
``` 

2) Can we just leave the default kwargs or do they need to be specified? Ideally the user would not have to worry about this.

Found an [issue](https://stackoverflow.com/questions/67021840/dask-df-to-parquet-oom) where the OOM was resolved by just using a client. Might be worth replicating.

**Comment by mrchtr** [comment]
Good points @PhilippeMoussalli!

In the example `dataframe.compute()` is mainly for illustrative purposes. Your proposed approach looks good and is probably the best way to proceed.

We just have to make sure, if a user is implementing a custom `DaskComponent` and calls for some reason a `compute()` that the defined client is used as well. 


> 1. We probably don't want to fix the client ...

I like this idea. I will follow your interface proposal in the implementation.

> 2. Can we just leave the default kwargs or do they need to be specified? Ideally the user would not have to worry about this.

Yes we can.

**Comment by RobbeSneyders** [comment]
Closed by https://github.com/ml6team/fondant/pull/410
